-- Idempotent reference data. Sample users are created through Supabase Auth,
-- so their profiles are generated by the on_auth_user_created trigger.
insert into public.achievements (title, description, required_hours, icon)
values
  ('Первый шаг', 'Первые подтверждённые волонтёрские часы.', 1, 'sparkles'),
  ('Надёжный помощник', '10 подтверждённых часов помощи сообществу.', 10, 'heart-handshake'),
  ('Активист', '25 подтверждённых волонтёрских часов.', 25, 'medal'),
  ('Опора сообщества', '50 подтверждённых волонтёрских часов.', 50, 'shield-check'),
  ('Амбассадор добра', '100 подтверждённых волонтёрских часов.', 100, 'award'),
  ('Легенда Qamqor', '250 подтверждённых волонтёрских часов.', 250, 'crown')
on conflict (required_hours) do update set
  title = excluded.title,
  description = excluded.description,
  icon = excluded.icon;
